### ISSUE TITLE
panic in runebuffer

### ISSUE THREAD

**Issue by slingamn** [ergochat/readline#69]
No repro case yet:

```
panic: runtime error: slice bounds out of range [2:1]

goroutine 10 [running]:
github.com/ergochat/readline.(*runeBuffer).WriteRunes.func1()
	github.com/ergochat/readline@v0.1.2/runebuf.go:141 +0x179
github.com/ergochat/readline.(*runeBuffer).refresh(0xc000064360, 0xc00046bc00)
	github.com/ergochat/readline@v0.1.2/runebuf.go:450 +0x54
github.com/ergochat/readline.(*runeBuffer).WriteRunes(0xc000064360, {0xc0000122ec, 0x1, 0x1})
	github.com/ergochat/readline@v0.1.2/runebuf.go:140 +0x1f5
github.com/ergochat/readline.(*runeBuffer).WriteRune(...)
	github.com/ergochat/readline@v0.1.2/runebuf.go:111
github.com/ergochat/readline.(*operation).readline(0xc0000643c0, 0x0)
	github.com/ergochat/readline@v0.1.2/operation.go:349 +0x143b
github.com/ergochat/readline.(*operation).Runes(0xc0000643c0)
	github.com/ergochat/readline@v0.1.2/operation.go:447 +0x1a7
github.com/ergochat/readline.(*operation).String(...)
	github.com/ergochat/readline@v0.1.2/operation.go:409
github.com/ergochat/readline.(*Instance).ReadLine(0x1?)
	github.com/ergochat/readline@v0.1.2/readline.go:208 +0x17
github.com/ergochat/readline.(*Instance).Readline(0x0?)
	github.com/ergochat/readline@v0.1.2/readline.go:213 +0x13
main.runClient.func1()
	./ircdog.go:331 +0x82
created by main.runClient in goroutine 1
	./ircdog.go:328 +0x210
```

**Comment by slingamn** [comment]
Repro steps:

1. Run `readline-demo`
2. Enter a single character at the prompt
3. Press Ctrl-T ("transpose characters") three times in a row

**Comment by slingamn** [comment]
There are probably more cases like this in runebuf.go...
